PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS ITEMS (
    ID VARCHAR(255) PRIMARY KEY,
    TIMESTAMP VARCHAR(30) NOT NULL,
    SOURCE VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    IMAGE_URL VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRICES (
    ID VARCHAR(255) NOT NULL,
    TIMESTAMP VARCHAR(30) NOT NULL,
    PRICE REAL,
    FOREIGN KEY(ID) REFERENCES ITEMS(ID)
);
